### ISSUE TITLE
[Bug] Window Resizing Bug in Latest Release

### ISSUE THREAD

**Issue by Maxinova** [peterfajdiga/karousel#26]
I've been encountering what seems to be a bug since the last release. When resizing a window (enlarging and reducing), it doesn't return to the center as expected. I find that I have to shift focus to another window for it to snap back to the center of the screen.

I've recorded a video that demonstrates the issue:

[https://youtu.be/YSyUbydLxyU](https://youtu.be/YSyUbydLxyU)

Here's a screenshot of my Karousel settings for reference:

![Screenshot_20240116_170503](https://github.com/peterfajdiga/karousel/assets/721025/0f796b84-1ae2-4a81-940a-f13107ebd332)

![Screenshot_20240116_170524](https://github.com/peterfajdiga/karousel/assets/721025/5eb6266c-834b-4fc7-86ca-d29d25c44899)

And here's my neofetch output:
```

                   -`                  
                  .o+`                   ---------------
                 `ooo/                   OS: Arch Linux x86_64
                `+oooo:                  Host: Micro-Star International Co., Ltd. MAG
               `+oooooo:                 Kernel: 6.7.0-4-cachyos
               -+oooooo+:                Uptime: 6 mins
             `/:-:++oooo+:               Packages: 1483 (pacman), 1 (flatpak), 2 (sna
            `/++++/+++++++:              Shell: zsh 5.9
           `/++++++++++++++:             Resolution: 3840x2160, 1920x1080, 5120x1440
          `/+++ooooooooooooo/`           DE: Plasma 5.27.10 (Wayland)
         ./ooosssso++osssssso+`          WM: kwin_wayland_wr
        .oossssso-````/ossssss+`         WM Theme: Breeze
       -osssssso.      :ssssssso.        Theme: Breeze Dark [Plasma], Breeze [GTK3]
      :osssssss/        osssso+++.       Icons: Tela-circle-dark [Plasma], Tela-circl
     /ossssssss/        +ssssooo/-       Terminal: alacritty
   `/ossssso+/:-        -:/+osssso+-     CPU: AMD Ryzen 7 5800X (16) @ 4.851GHz
  `+sso+:-`                 `.-/+oso:    GPU: AMD ATI Radeon RX 7900 XT/7900 XTX
 `++:.                           `-/+/   Memory: 46284MiB / 64222MiB
 .`                                 `/
```

**Comment by peterfajdiga** [comment]
@Maxinova I can't see the Youtube video you shared, as it's set to private.

**Comment by Maxinova** [comment]
My bad, it should be working now.

**Comment by peterfajdiga** [comment]
Hi, can you check whether the bug persists in the attached version of Karousel?
[karousel_0_7.tar.gz](https://github.com/peterfajdiga/karousel/files/14221419/karousel_0_7.tar.gz)

**Comment by Maxinova** [comment]
Yeah it's fixed ! Thank you very much.
